### ISSUE TITLE
About the Symbol table ,string table address

### ISSUE THREAD

**Issue by vedon** [facebook/fishhook#11]
I do not understand why the  linkedit_base = (uintptr_t)slide + linkedit_segment->vmaddr - linkedit_segment->fileoff;

not 

linkedit_base = (uintptr_t)slide + linkedit_segment->vmaddr;

**Comment by grp** [comment]
I'm not quite sure either, the names seem like what you said makes more sense. But it works this way — is this causing an issue for you?

**Comment by vedon** [comment]
@grp 
![screen shot 2015-07-21 at 10 02 20 am](https://cloud.githubusercontent.com/assets/1811570/8791585/51b72a9a-2f8f-11e5-9486-f7e10bcb6082.png)

I'm not sure the linkedit_base is the pic describe or not

**Comment by vedon** [comment]
@grp  Do you have any idea to get the symbol from __DATA _data section . the symbol read from local Mach-O file is more than runtime Mach-O file .And I found the symbol in __DATA _data section is gone in runtime.

**Comment by grp** [comment]
I'm not sure; is that related to fishhook?

**Comment by vedon** [comment]
@grp  Nope ,I just want to ask you something and figure out what the meaning of linkedit_base
