### ISSUE TITLE
hook not successful in iOS9

### ISSUE THREAD

**Issue by scutautoyy** [facebook/fishhook#16]
It worked in iOS8.x and all lower versions but not in iOS9, I found the reason is that Apple add a new segname of section called "__DATA_CONST" in iOS9, function "rebind_symbols_for_image" just check if segname is "__DATA" ("(strcmp(cur_seg_cmd->segname, SEG_DATA) != 0)"), so when do enumurate to  "__DATA_CONST" section, code doesn't work.

**Comment by kastiglione** [comment]
Support was added in #12.
