### ISSUE TITLE
linkedit_base always equal mach_header。

### ISSUE THREAD

**Issue by AloneMonkey** [facebook/fishhook#19]
// Find base symbol/string table addresses
    uintptr_t linkedit_base = (uintptr_t)slide + linkedit_segment->vmaddr - linkedit_segment->fileoff;

the value of linkedit_base is always equal mach_header,why not substitute mach_header  for linkedit_base？

**Comment by grp** [comment]
It may be in practice, but the format doesn't require that. It could be different.
