### ISSUE TITLE
Create a new release for the API change in Commit 8dbd09b and make the Podspec point to it.

### ISSUE THREAD

**Issue by tirodkar** [facebook/fishhook#20]
The merging of PR #18 led to a break in the API. We have made the required changes, however the podspec still points to version 0.1. We use Fishhook rigorously for testing and this change breaks all our pods dependencies. Could we please create a new release for this change and have it added to the podspec (or just have the podspec pointing to head)? 

Also, it would be great if we regularly update the podspec with any new releases.

**Comment by grp** [comment]
In general, for Facebook projects I suggest using commit hashes rather than versions — we don't use versions internally and so don't track them closely on CocoaPods.

I'll keep this open to update the published podspec when I get a chance. It'll probably be version 0.2.

**Comment by tirodkar** [comment]
Thanks. We'll point to HEAD right now instead of the commit so we know if there are any further updates. It would be great if a release is cut if there are any further commits :)

**Comment by toddlee** [comment]
I can't get fishhook using cocoapods.
Not sure this issue is related.

[!] Unable to find a specification for `fishhook`

**Comment by tirodkar** [comment]
Hey grp, just checking - are you planning to create a new release soon? Could we get an ETA if possible?

**Comment by tirodkar** [comment]
Closing this thanks to the new 0.2 release update.
