### ISSUE TITLE
hook symbol "connect" not successfully

### ISSUE THREAD

**Issue by akq41** [facebook/fishhook#23]
I use it in ipad(iOS 9.2), but I can not hook it successfully.
I've written the following code : 

 >rebind_symbols((struct rebinding[1]){
 >　　　{ "connect", (void *)my_connect, (void *)&ori_connect},
 >}, 1)；

I try to set breakpoint "connect" after rebinding. I get the stack:

> frame #0: 0x21623adc libsystem_kernel.dylib`__connect

> frame #1: 0x216747d4 libsystem_network.dylib`netcore_create_control_socket + 228    

>frame #2: 0x21661b1e libsystem_network.dylib`get_host_counts + 62    

>frame #3: 0x2168813a libsystem_network.dylib`tcp_connection_destination_create + 186

>frame #4: 0x21666000 libsystem_network.dylib`tcp_connection_destination_add + 52

>frame #5: 0x21665fc4 libsystem_network.dylib`__tcp_connection_start_host_block_invoke + 96  
  
>frame #6: 0x216828ca libsystem_network.dylib`tcp_connection_host_resolve_result + 1450   

>frame #7: 0x215f1a2e libsystem_dnssd.dylib`handle_addrinfo_response + 322    

>frame #8: 0x215f04b8 libsystem_dnssd.dylib`DNSServiceProcessResult + 528    

>frame #9: 0x0049d66e libdispatch.dylib`_dispatch_source_latch_and_call + 2246   

>frame #10: 0x0048bc24 libdispatch.dylib`_dispatch_source_invoke + 712    

>frame #11: 0x00494050 libdispatch.dylib`_dispatch_queue_drain + 644    

>frame #12: 0x0048cef8 libdispatch.dylib`_dispatch_queue_invoke + 284    

>frame #13: 0x00495a8c libdispatch.dylib`_dispatch_root_queue_drain + 420    

>frame #14: 0x004958e6 libdispatch.dylib`_dispatch_worker_thread3 + 102   

>frame #15: 0x216c7b28 libsystem_pthread.dylib`_pthread_wqthread + 1024   

>frame #16: 0x216c7718 libsystem_pthread.dylib`start_wqthread + 8

netcore_create_control_socket assembly :

>0x216747ca <+218>: mov    r0, r4
    
>0x216747cc <+220>: str.w  r10, [sp, #0x20]
    
>0x216747d0 <+224>: blx    0x21623adc           ; __connect
    
>0x216747d4 <+228>: cmp    r0, #0x0
    
>0x216747d6 <+230>: beq    0x21674806           ; <+278>
    
>0x216747d8 <+232>: mov    r0, r4
    
>0x216747da <+234>: blx    0x2169b1ec           ; symbol stub for: __destroy_helper_block_73

Why libsystem_network.dylib call connect use blx + direct address?  Thanks

**Comment by Quakerfang** [comment]
I've got the same problem. Have you solved the problem?

**Comment by grp** [comment]
Calls from system libraries into functions are often optimized and won't go through the tables that fishhook hooks. Based on your stack trace, it looks like that might be what's happening here. Sadly, there's not much possibility for fixing that without finding a different hooking method.
