### ISSUE TITLE
can fishhook hook c function in static framework?

### ISSUE THREAD

**Issue by wangdetong** [facebook/fishhook#44]
A demo project have import a static framework, and the framework have a function named `myF`. I want to hook it and replace to  `hook_myFu`, but it not work.
Is fishhook hook dylib function only? or I do something wrong?
Thank you!

code in simple ViewController
```
static void (*orig_myFunction)(void);
void hook_myFu(){
    NSLog(@" 123");
}
viewDidLoad {
    [super viewDidLoad];
    
    struct rebinding open_rebinding = {"myF", hook_myFu, (void *)&orig_myFunction};
    rebind_symbols((struct rebinding[1]){open_rebinding}, 1);
    myF();
}
```

**Comment by kastiglione** [comment]
Yes, fishhook can only hook functions in other dylibs. I'm not aware of an alternative for static libraries.

**Comment by wangdetong** [comment]
Thank you for your help, good luck!

**Comment by wangdetong** [comment]
a simple question:
Why Fishhook can hook functions in other dylibs ,but can't hook static libs.
I want know the real reason, so that i can learn more about the dyld.
Or we don't talk about Fishhook, is the functions in static lib can be hook?
Thank you very much!

**Comment by wangdetong** [comment]
I guess:
  There is not symbol table after compile the static libs, so that we can't rebind symbol.
But dylib's symbol table is exist when the program run.
Is it right?
