### ISSUE TITLE
we find a memory leak in fishhook function "prepend_rebindings",line 67

### ISSUE THREAD

**Issue by rosen0510** [facebook/fishhook#48]
`  new_entry->rebindings = (struct rebinding *) malloc(sizeof(struct rebinding) * nel);`
This malloc region didn't free in appropriate position

**Comment by dinhviethoa** [comment]
In fishhook, entries are not removed.
Then, we keep them in memory forever.

**Comment by rosen0510** [comment]
The "new_enry->rebindings" can't be accessed in anywhere after that function, why don't you free it ? It's there any special reason ?

**Comment by dinhviethoa** [comment]
It can be accessed via new_entry.

**Comment by rosen0510** [comment]
But in function "rebind_symbos_image" ,line 190, you freed the "rebinds_head" which is the same as "new_entry".

**Comment by dinhviethoa** [comment]
Could you send a pull request to solve it then?

**Comment by rosen0510** [comment]
ok

**Comment by Megra** [comment]
https://github.com/facebook/fishhook/commit/06cfb582bd9279879894bfd9cc9e562cc6e4b01e
