### ISSUE TITLE
hook stat

### ISSUE THREAD

**Issue by SongZhaoJie** [facebook/fishhook#55]
I'll use fishhook hook stat to get the call all the time  thank you
![2018-09-05 2 24 26](https://user-images.githubusercontent.com/29090582/45074802-6fa13480-b117-11e8-8fc0-689ac45bc997.png)
![2018-09-05 2 25 17](https://user-images.githubusercontent.com/29090582/45074840-92cbe400-b117-11e8-93c3-dce381fe29ee.png)

**Comment by dinhviethoa** [comment]
It's unclear what you're looking for. Could you file a new issue where you describe what you'd like to do, what's the expected behavior of fishhook and what's the actual behavior?

Thanks!

**Comment by SongZhaoJie** [comment]
I want to intercept   “stat” Underlying c language .  Do you know how to intercept
