### ISSUE TITLE
i use fishhook like this,rebind_symbols((struct rebinding[1]){{"SCDynamicStoreCopyProxies", new_SCDynamicStoreCopyProxies}}, 1);  everything is ok in ios7,but  new_SCDynamicStoreCopyProxies never called in iOS 8,can you tell me what cause it happen.ca you fix it?

### ISSUE THREAD

**Issue by jacklibonnie** [facebook/fishhook#6]

**Comment by Qingfeng0203** [comment]
I meet the same problem these days, do you have any ideas about it ?

**Comment by grp** [comment]
Whether fishhook works is dependent on a number of details of the exact libraries and calls you're trying to hook — it's hard to say whether it'll work in any specific case.
