### ISSUE TITLE
Hook called in iOS simulator but not called on-device

### ISSUE THREAD

**Issue by NSExceptional** [facebook/fishhook#75]
I'm trying to hook `os_log_shim_enabled`, a private function in CoreFoundation that changes how `NSLog()` behaves. Here's my code:

```objc
static BOOL FLEXDidHookNSLog = NO;
BOOL (*orig_os_log_shim_enabled)() = nil;
BOOL my_os_log_shim_enabled() {
    return NO;
}

@implementation FLEXSystemLogViewController

+ (void)load {
    FLEXDidHookNSLog = rebind_symbols((struct rebinding[1]) {
        "os_log_shim_enabled",
        (void *)my_os_log_shim_enabled,
        (void **)&orig_os_log_shim_enabled
    }, 1) == 0;
}

...
```

As the title says, it works in the simulator, but has no effect on-device. I came across [this issue,](https://github.com/facebook/fishhook/issues/28) but I don't really understand what might be going wrong. `rebind_symbols` returns 0 in both cases, and stepping through the code running on-device I can see that fishhook does indeed find the symbol and does replace it here from within `__la_symbol_ptr`:

```objc
static void perform_rebinding_with_section(...) {
    ...
--> indirect_symbol_bindings[i] = cur->rebindings[j].replacement;
    ...
}
```

When I set a breakpoint for the original function, I can see it's being called instead of my replacement. Here's a screenshot of the debugger:

<img width="970" alt="Screenshot 2020-02-19 at 1 37 20 PM" src="https://user-images.githubusercontent.com/8371943/74869177-2057bf80-531d-11ea-933c-0183020addec.png">

Is `_CFLogvEx3` just not using the lazy binding in this case? Does that mean I'll need to use another hooking library that uses trampolines?

**Comment by saagarjha** [comment]
I think calls to symbols in the shared cache just go through directly, since they're all linked together? Since the simulator doesn't use a shared cache (to my knowledge) it must go through a PLT stub, which fishhook can intercept.

**Comment by NSExceptional** [comment]
Ah, that makes sense. Well, now anyone else running into this will hopefully find this issue through Google with this explanation. Thanks!
