### ISSUE TITLE
How thread-safe is fishhook

### ISSUE THREAD

**Issue by michaeleisel** [facebook/fishhook#76]
I want to hook `pthread_create` in `main`, but I'm curious if there can be any tearing or otherwise bugs due to thread safety. I don't mind if it's undefined whether concurrent calls use the old or the new function, I just want to be sure that there won't be any peripheral bugs.

**Comment by swolchok** [comment]
If you hook in `main` (i.e., before any other threads are created), how would there be any concurrent calls?

**Comment by michaeleisel** [comment]
Fair point

**Comment by swolchok** [comment]
Sounds like that answered your question, so closing. Thanks for asking!
