### ISSUE TITLE
I can not hook gcd functions

### ISSUE THREAD

**Issue by joker75195** [facebook/fishhook#8]
I try to hook dispatch_async function，but it do not work。
here is the code sample：
int result = rebind_symbols(struct rebinding[1]){{"dispatch_async",xcsandbox_dispatch_async}},1);
//result is 0 (no error)
then i call dispatch_async(dispatch_get_global_queue(0,0),{
     //do some thing;
});

it call system default dispatch_async function, not my xcsandbox_dispatch_async.
i do not know why,and how to fix this. if you know,please reply me.

thx

ASAP

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
