### ISSUE TITLE
Will Apple reject the app if I use fishhook in app?

### ISSUE THREAD

**Issue by GangWang** [facebook/fishhook#9]
I have to user fishhook do some work,  Will Apple reject the app if I use fishhook in app?    may I have a answer, many thanks.

**Comment by kastiglione** [comment]
Hi @GangWang 

Unfortunately, you can expect that an app submission including fishhook will be rejected.

**Comment by grp** [comment]
It's impossible to know for sure, but as @kastiglione said, we wouldn't suggest it.

**Comment by GangWang** [comment]
;)  thanks,    well,   I guess there is no other way to hook c function in my app, is there?

**Comment by swinpa** [comment]
Hi @GangWang
did you commit your app to appstore with including fishhook?
is that rejected by appstore?
